### ISSUE TITLE
create_about_ayataka

### ISSUE THREAD

**Issue by ayataka-bcts** [VG-Tech-Dojo/vg-1day-2017-05-27#14]

**Comment by ayataka-bcts** [comment]
#29

**Comment by tamamu** [comment]
https://github.com/VG-Tech-Dojo/vg-1day-2017-05-27/issues/15#issuecomment-304425129
さっきの説明ちょっと間違ってました！正しくはコミットメッセージに #14 みたいにissueの番号を付けるといいみたいです。
